### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by oaosdpo** [CyberTitus/GPhisher#1]
The program didn't output a link, I tried it on termux.

**Comment by oaosdpo** [comment]
> link doesn't work when it says ''send link to victim'' it doesn't show a link. broken.

google new specifically. also when you've made a change to the bug can you make a google otp (backup codes) page too?

**Comment by oaosdpo** [comment]
> > link doesn't work when it says ''send link to victim'' it doesn't show a link. broken.
> 
> google new specifically. also when you've made a change to the bug can you make a google otp (backup codes) page too?

when tried in termux. is something else supposed to be used?

**Comment by CyberTitus** [comment]
> > > link doesn't work when it says ''send link to victim'' it doesn't show a link. broken.
> > 
> > 
> > google new specifically. also when you've made a change to the bug can you make a google otp (backup codes) page too?
> 
> when tried in termux. is something else supposed to be used?

Can you please provide a screenshot

**Comment by CyberTitus** [comment]
I made the tool to be executed on Linux (Debian)
