### ISSUE TITLE
Upgraded website

### ISSUE THREAD

**Issue by D4RKH0R1Z0N** [CyberTitus/GPhisher#2]
Hello! Here is the most latest and upgrade Google Login Phishing Page : https://github.com/D4RKH0R1Z0N/GPhish

**Comment by AbdulRKB** [comment]
_A new version of the tool has been published right now. Thank you from bringing attention on this._

**Comment by D4RKH0R1Z0N** [comment]
Can you add me in README.md? For helping?

**Comment by AbdulRKB** [comment]
> Can you add me in README.md?
- [x] *Your name has been added into the README.md file*

**Comment by D4RKH0R1Z0N** [comment]
Ok thank you!
