### ISSUE TITLE
It says "waiting for password to be entered" and thats it nothing more

### ISSUE THREAD

**Issue by Soft-JUICE** [CyberTitus/GPhisher#4]
It says "waiting for password to be entered" and thats it nothing

**Comment by AbdulRKB** [comment]
Please run the command `apt install php7.4-cli` to install PHP. I have tried the tool on a different device just now and came across the same error, I fixed it just by installing PHP.

**Comment by AbdulRKB** [comment]
There has also been some errors with JavaScript which are now fixed 👍
